import './globals.css'
import Nav from './components/Nav'
import { Kdam_Thmor_Pro } from 'next/font/google'
import Footer from './components/Footer'

 
const roboto = Kdam_Thmor_Pro ({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body  className={roboto.className} >
      <Nav /><div className='bg-purple-700'> {children} <Footer/></div></body>
    </html>
  )
}
